import Foundation

enum AppStrings {
    private static let localizationBundle: Bundle = {
        if let resourceURL = Bundle.main.resourceURL,
           let bundle = Bundle(
               url: resourceURL.appendingPathComponent(
                   "DroidMatchMac_DroidMatchApp.bundle",
                   isDirectory: true
               )
           ) {
            return bundle
        }
        return .module
    }()

    static let appName = value("DroidMatch")
    static let devices = value("Devices")
    static let files = value("Files")
    static let media = value("Media")
    static let images = value("Images")
    static let imageAlbums = value("Image Albums")
    static let videos = value("Videos")
    static let appSandbox = value("App Sandbox")
    static let transfers = value("Transfers")
    static let diagnostics = value("Diagnostics")
    static let localFirst = value("Local first")
    static let adbFoundation = value("USB discovery through the product ADB boundary")
    static let refresh = value("Refresh")
    static let refreshDevices = value("Refresh devices")
    static let runningAppWasReplaced = value("A newer DroidMatch build is ready")
    static let runningAppWasReplacedDetail = value("This running copy cannot adopt the replaced App safely. Device work has stopped; quit and reopen DroidMatch before connecting again.")
    static let quitDroidMatch = value("Quit DroidMatch")
    static let deviceOverview = value("Your Android devices")
    static let deviceOverviewDetail = value("Private, local discovery. Hardware serials stay outside the interface.")
    static let visible = value("Visible")
    static let ready = value("Ready")
    static let transport = value("Transport")
    static let lookingForDevices = value("Looking for devices…")
    static let noDevices = value("No Android devices found")
    static let noDevicesDetail = value("Connect a device by USB, unlock it, and approve the ADB prompt if Android asks.")
    static let adbUnavailable = value("ADB is unavailable")
    static let discoveryTimedOut = value("Device discovery timed out")
    static let discoveryUnavailable = value("Device discovery is unavailable")
    static let staleDeviceDetail = value("The last device snapshot is shown as stale. Refresh before starting a session.")
    static let discoveryFailureDetail = value("Check the Android platform tools and try again.")
    static let androidDevice = value("Android device")
    static let trustedAndroidDevices = value("Trusted Android devices")
    static let trustedAndroidDevicesDetail = value("Pairing records saved securely in this Mac's Keychain.")
    static let trustedDevicesUnavailable = value("Saved trust records are temporarily unavailable.")
    static let trustedDevicesSystemRequestPending = value("macOS is still checking saved trust. This display-only check will not open an authentication prompt; if it never returns, reopen DroidMatch.")
    static let noTrustedDevices = value("No Android devices are currently trusted.")
    static let lastUsed = value("Last used: %@")
    static let removeTrust = value("Remove trust")
    static let removeTrustedDevice = value("Remove trusted device?")
    static let removeTrustedDeviceDetail = value("%@ will need to pair again. Any active session will be disconnected first.")
    static let removeAndDisconnect = value("Remove and disconnect")
    static let keepDevice = value("Keep")
    static let trustRemovalFailed = value("Trust wasn’t removed")
    static let trustRemovalFailedDetail = value("DroidMatch could not confirm that the Keychain record was removed. The device remains listed as trusted; try again before reconnecting.")
    static let stale = value("Stale")
    static let unauthorized = value("Approval needed")
    static let offline = value("Offline")
    static let unavailable = value("Unavailable")
    static let connect = value("Connect")
    static let reconnect = value("Reconnect")
    static let startPairing = value("Start pairing")
    static let disconnect = value("Disconnect")
    static let browseFiles = value("Browse Files")
    static let goToDevices = value("Go to Devices")
    static let tryAgain = value("Try again")
    static let sessionIdle = value("No active session")
    static let connectingSecurely = value("Connecting securely…")
    static let connectingSecurelyDetail = value("Creating a private USB forward and checking the Android device identity. If macOS shows a Keychain prompt, it is authorizing DroidMatch to read this device’s saved pairing key—not requesting an Apple signing certificate. DroidMatch has no password field; enter a Mac login password only in the macOS system dialog.")
    static let pairingRequired = value("Pair this Mac")
    static let pairingRequiredDetail = value("On Android, open DroidMatch, enable Secure USB, then open the two-minute pairing window before continuing here.")
    static let startingPairing = value("Starting pairing…")
    static let startingPairingDetail = value("Waiting for the Android pairing window and a fresh device challenge.")
    static let confirmPairingCode = value("Confirm the pairing code")
    static let confirmPairingCodeDetail = value("Compare the six digits on both devices. Approve only when they match exactly.")
    static let finishingPairing = value("Securing the session…")
    static let finishingPairingDetail = value("Both approvals are being confirmed before credentials are stored and the session reconnects.")
    static let secureSessionReady = value("Secure session ready")
    static let secureSessionReadyDetail = value("Device identity and both session proofs are verified. File browsing is now available.")
    static let disconnecting = value("Disconnecting…")
    static let disconnectingDetail = value("Closing the session and removing its private ADB forward.")
    static let connectionFailed = value("Couldn’t connect securely")
    static let sessionDeviceUnavailable = value("The selected device is no longer connected. Refresh the device list and try again.")
    static let sessionDeviceNotReady = value("Unlock Android and approve the ADB prompt before connecting.")
    static let sessionTimedOut = value("The USB connection timed out. Check the cable and try again.")
    static let sessionPairingRejected = value("Pairing was not approved. Open a new pairing window on Android before retrying.")
    static let sessionIdentityChanged = value("The Android identity changed during pairing, so no trust was saved.")
    static let secureEndpointRequired = value("Secure USB required")
    static let sessionSecureEndpointRequired = value("The Android diagnostic endpoint is active. In DroidMatch, turn off the current USB connection, enable Secure USB, then retry.")
    static let sessionCredentialsUnavailable = value("The saved pairing record could not be read. If macOS showed a Keychain prompt, allow DroidMatch there and try again. If it remains unavailable, remove trust and pair the device again.")
    static let sessionAuthenticationFailed = value("The saved pairing could not prove this device identity. Pair again before accessing files.")
    static let sessionConnectionUnavailable = value("Open DroidMatch on Android and enable Secure USB, then retry. Nothing was exposed and the USB forward was closed.")
    static let compareCodeWithDevice = value("Compare this code with the one shown on %@.")
    static let pairingCodeAccessibility = value("Pairing code %@")
    static let codesDoNotMatch = value("Codes don’t match")
    static let codesMatch = value("Codes match")
    static let filesNeedSession = value("Files need an authenticated session")
    static let filesNeedSessionDetail = value("Connect and authenticate a device to browse and manage its files.")
    static let mediaNeedSession = value("Media needs an authenticated session")
    static let mediaNeedSessionDetail = value("Connect and authenticate a device to browse photos, albums, and videos.")
    static let transfersNeedSession = value("No active transfer session")
    static let transfersNeedSessionDetail = value("Connect and authenticate a device before starting or viewing transfers.")
    static let diagnosticsNeedSession = value("Diagnostics need an authenticated session")
    static let diagnosticsNeedSessionDetail = value("Connect and authenticate a device to view structured transport, permission, storage, and battery status.")
    static let authenticatedFiles = value("Authenticated Android files")
    static let authenticatedMedia = value("Authenticated Android media")
    static let back = value("Back")
    static let loadingFiles = value("Loading files…")
    static let loadingMediaItems = value("Loading media…")
    static let folderIsEmpty = value("This location is empty")
    static let folderIsEmptyDetail = value("No items are visible with the Android permissions currently granted.")
    static let mediaLocationIsEmpty = value("No media is visible here")
    static let mediaLocationIsEmptyDetail = value("This category or album has no items visible with the current Android media permission.")
    static let loadMore = value("Load more")
    static let filePermissionRequired = value("Android permission is required for this location.")
    static let fileLocationUnavailable = value("This Android location is no longer available.")
    static let fileOperationUnsupported = value("This provider does not support directory listing here.")
    static let fileResponseInvalid = value("Android returned an invalid directory response.")
    static let fileConnectionUnavailable = value("The directory could not be loaded over the secure session.")
    static let unnamedItem = value("Unnamed item")
    static let writable = value("Writable")
    static let openFolder = value("Open folder")
    static let download = value("Download")
    static let downloadFile = value("Download file")
    static let previewMedia = value("Preview media")
    static let loadingMediaLibrary = value("Loading media library…")
    static let recheckMediaAccess = value("Recheck Media Access")
    static let recheckMediaAccessDetail = value("Recheck Android permissions and reload every media category.")
    static let mediaLibraryUnavailable = value("Media library is unavailable")
    static let mediaAccessRequired = value("Android media access is required")
    static let mediaPhotoAccessRequiredDetail = value("In DroidMatch on Android, grant or reselect photo access, then recheck access here. Images and Albums use the same Android permission; writable Images can still receive uploads without revealing existing items.")
    static let mediaVideoAccessRequiredDetail = value("In DroidMatch on Android, grant video access, then recheck access here. Writable Videos can still receive an upload without revealing existing items.")
    static let mediaCategoryUnavailable = value("This media category is unavailable")
    static let mediaCategoryUnavailableDetail = value("The connected Android version did not advertise this DroidMatch media root.")
    static let mediaUploadFreshOnlyDetail = value("Media uploads create a new Android item. If interrupted, they cannot pause or resume and must restart.")
    static let loadingPreview = value("Loading preview…")
    static let previewUnavailable = value("Preview unavailable")
    static let showAsGrid = value("Show as Grid")
    static let showAsList = value("Show as List")
    static let settings = value("Settings")
    static let helpMenuTitle = value("DroidMatch Help")
    static let helpWindowTitle = value("DroidMatch Help")
    static let helpSubtitle = value("Connect, pair, and transfer privately over USB.")
    static let helpGetConnected = value("Get connected")
    static let helpEnableSecureUSB = value("Open DroidMatch on Android and enable Secure USB.")
    static let helpApproveADB = value("Connect by USB, unlock Android, and approve the ADB prompt.")
    static let helpComparePairingCode = value("Refresh on Mac, choose the device, and compare the six-digit pairing code on both screens.")
    static let helpBrowseAndTransfer = value("Browse and transfer")
    static let helpUseFilesAndMedia = value("Use Files and Media after the secure session is ready.")
    static let helpPermissionsAreLive = value("Android permissions are checked live. Grant or reselect access on Android when asked.")
    static let helpUseTransfers = value("Use Transfers to pause, resume, retry, or review saved work.")
    static let helpTroubleshooting = value("If something doesn’t work")
    static let helpNoDevice = value("No device: check the data cable, unlock Android, approve ADB, then refresh.")
    static let helpAuthenticationFailed = value("Authentication failed: reopen Secure USB and a new two-minute pairing window on Android.")
    static let helpInterruptedTransfer = value("Interrupted transfer: reconnect the same Android device and review Transfers.")
    static let helpPrivacy = value("Privacy by default")
    static let helpLocalUSB = value("DroidMatch keeps transfers local over USB and binds ADB forwards to this Mac.")
    static let helpSerialPrivacy = value("Hardware serials stay out of the interface and normal logs.")
    static let helpKeychainPrivacy = value("Pairing records stay in Keychain; opening Help never reads credentials or connects a device.")
    static let helpKeychainConnectionPrompt = value("Only an explicit device connection reads a saved pairing key. A macOS Keychain prompt authorizes that read; it is not an Apple signing request, and DroidMatch has no password field. A rebuilt local ad-hoc app may prompt again because macOS can treat its changed code signature as a new app identity.")
    static let fileBrowsing = value("File Browsing")
    static let mediaGridByDefault = value("Show media folders as a grid by default")
    static let mediaGridByDefaultDetail = value("You can still switch between grid and list from the file toolbar.")
    static let transferNotifications = value("Transfer Notifications")
    static let notifyWhenTransfersFinish = value("Notify when transfers finish")
    static let transferNotificationsDetail = value("Notifications require macOS permission. Existing history and cancelled transfers never generate alerts.")
    static let downloadCompletedNotification = value("Download completed")
    static let uploadCompletedNotification = value("Upload completed")
    static let transferFailedNotification = value("Transfer failed")
    static let transferInterruptedNotification = value("Transfer needs attention")
    static let transferFinished = value("Transfer finished")
    static let sort = value("Sort")
    static let sortByName = value("Name")
    static let sortByDate = value("Date Modified")
    static let sortBySize = value("Size")
    static let ascending = value("Ascending")
    static let descending = value("Descending")
    static let downloadCouldNotStart = value("Download couldn’t start")
    static let downloadCouldNotStartDetail = value("The selected destination or Android file path is no longer valid.")
    static let upload = value("Upload")
    static let uploadCouldNotStart = value("Upload couldn’t start")
    static let uploadCouldNotStartDetail = value("Choose a supported regular file and writable Android directory, then check queue recovery status.")
    static let batchUploadCouldNotStart = value("Selected files couldn’t be added")
    static let batchUploadCouldNotStartDetail = value("Choose up to 100 regular files with unique supported names.")
    static let batchUploadUnavailable = value("Selected files weren’t added")
    static let batchUploadUnavailableDetail = value("No transfer started. Check queue recovery status and try again.")
    static let batchUploadPartiallyStarted = value("Some selected files couldn’t be added")
    static let batchUploadPartiallyStartedDetail = value("Any accepted files remain in Transfers. Review the queue before retrying the rest.")
    static let newFolder = value("New Folder")
    static let folderName = value("Folder name")
    static let create = value("Create")
    static let folderCouldNotBeCreated = value("Folder couldn’t be created")
    static let folderNameInvalid = value("Choose a name without slashes or control characters.")
    static let folderAlreadyExists = value("An item with this name already exists.")
    static let folderPermissionRequired = value("Android no longer allows changes in this location.")
    static let folderParentUnavailable = value("This Android location is no longer available.")
    static let folderCreationUnsupported = value("This provider does not support creating folders here.")
    static let folderCreationUnavailable = value("The folder could not be created over the secure session.")
    static let itemChangedBeforeMutation = value("The item changed or is no longer writable. Refresh and try again.")
    static let itemUnavailableForMutation = value("This item or its Android location is no longer available.")
    static let renameUnsupported = value("This provider does not support renaming this item.")
    static let deleteUnsupported = value("This provider does not support deleting this item.")
    static let renameUnavailable = value("The item could not be renamed over the secure session.")
    static let deleteUnavailable = value("The item could not be deleted over the secure session.")
    static let batchDeleteUnavailable = value("The selected items could not be deleted over the secure session.")
    static let partialDeletionDetail = value("Some items were deleted before Android returned an error. The current folder was refreshed; review it before trying again.")
    static let rename = value("Rename")
    static let renameItem = value("Rename Item")
    static let newName = value("New name")
    static let itemCouldNotBeRenamed = value("Item couldn’t be renamed")
    static let delete = value("Delete")
    static let deleteItem = value("Delete this item?")
    static let deleteFileDetail = value("This file will be permanently removed from Android.")
    static let deleteFolderDetail = value("This folder and all of its contents will be permanently removed from Android.")
    static let itemCouldNotBeDeleted = value("Item couldn’t be deleted")
    static let searchFiles = value("Search this folder")
    static let searchMedia = value("Search this category or album")
    static let noSearchResults = value("No matching items")
    static let noSearchResultsDetail = value("Try a different name in this folder.")
    static let noMediaSearchResultsDetail = value("Try a different name in this category or album.")
    static let refreshCurrentMediaItems = value("Refresh Current Media Items")
    static let refreshCurrentMediaItemsDetail = value("Reload only the current category or album.")
    static let select = value("Select")
    static let selected = value("Selected")
    static let notSelected = value("Not selected")
    static let selectAllLoaded = value("Select All Loaded")
    static let clearSelection = value("Clear Selection")
    static let done = value("Done")
    static let deleteSelectedItems = value("Delete selected items?")
    static let deleteSelectedItemsDetail = value("All selected files, folders, and folder contents will be permanently removed from Android.")
    static let someItemsCouldNotBeDeleted = value("Some items couldn’t be deleted")
    static let dropFilesToUpload = value("Drop files to upload")
    static let droppedFilesInvalid = value("Some dropped files couldn’t be added")
    static let droppedFilesInvalidDetail = value("Drop up to 100 regular files with unique names into a writable Android folder.")
    static let downloadSelected = value("Download Selected")
    static let batchDownloadCouldNotStart = value("Selected files couldn’t be downloaded")
    static let batchDownloadCouldNotStartDetail = value("Select readable files with unique names and an empty destination folder.")
    static let batchDownloadUnavailable = value("No selected downloads started")
    static let batchDownloadUnavailableDetail = value("No download started. Check queue recovery status and try again.")
    static let batchDownloadPartiallyStarted = value("Some selected downloads started")
    static let batchDownloadPartiallyStartedDetail = value("Accepted downloads remain in Transfers. Only unaccepted files stay selected; review the queue before retrying.")

    static func selectedCount(_ count: Int) -> String {
        String(format: value("%d selected"), count)
    }
    static let dismiss = value("Dismiss")
    static let secureTransfers = value("Secure transfers")
    static let persistentQueueDetail = value("Pending work is saved privately for this authenticated device. Resume paused items after reconnecting.")
    static let queuePersistencePreparing = value("Transfer recovery storage is being checked. New transfers will be available in a moment.")
    static let queuePersistenceFailed = value("Queue recovery storage is unavailable. New transfers are blocked to avoid losing recovery state.")
    static let transferSubmissionTemporarilyUnavailable = value("Transfers are temporarily unavailable. Check the recovery status above.")
    static let clearCompleted = value("Clear Completed")
    static let clearCompletedDetail = value("Remove successful, fully settled transfers from this queue.")
    static let completedTransfersRemain = value("Some completed transfers remain")
    static let transferActionFailed = value("Couldn’t update transfer")
    static let transferActionFailedDetail = value("The transfer changed or its recovery state could not be saved. Review the current queue status and try again.")
    static let noTransfers = value("No transfers yet")
    static let noTransfersDetail = value("Download a readable Android file, or upload a local file into a writable Android directory.")
    static let pause = value("Pause")
    static let resume = value("Resume")
    static let cancel = value("Cancel")
    static let retryCleanup = value("Retry Cleanup")
    static let remove = value("Remove")
    static let transferQueued = value("Queued")
    static let transferRunning = value("Downloading")
    static let transferUploading = value("Uploading")
    static let transferRetrying = value("Retrying")
    static let transferPausing = value("Pausing")
    static let transferPaused = value("Paused")
    static let transferCleaning = value("Cleaning Up")
    static let transferCompleted = value("Completed")
    static let transferFailed = value("Failed")
    static let transferCancelled = value("Cancelled")
    static let transferInterrupted = value("Interrupted")
    static let transferRetryingDetail = value("The transfer was interrupted. DroidMatch will retry automatically.")
    static let transferCleaningDetail = value("DroidMatch is securely discarding the resumable Android partial before confirming cancellation.")
    static let transferCleanupRetryDetail = value("Android cleanup could not be confirmed. Keep the device connected, then retry cleanup; the final destination will not be deleted.")
    static let transferFailureConnectionDetail = value("The connection ended. Reconnect Android, then start the transfer again from Files or Media.")
    static let transferFailureAndroidPermissionDetail = value("Access changed on Android. Reauthorize the folder or media category, then start again.")
    static let transferFailureRemoteUnavailableDetail = value("The Android item or destination is no longer available. Refresh Files or Media, then start again.")
    static let transferFailureDestinationConflictDetail = value("Another transfer or existing item uses this destination. Choose a different destination and start again.")
    static let transferFailureInvalidRequestDetail = value("The source or destination changed. Refresh or reselect it, then start again.")
    static let transferFailureIntegrityDetail = value("The integrity check failed. Check the cable, then start again.")
    static let transferFailureAndroidStorageDetail = value("Android storage is read-only or unavailable. Check storage access, then start again.")
    static let transferFailureUnsupportedDetail = value("This Android device or provider does not support this transfer.")
    static let transferFailureLocalSourceDetail = value("The selected Mac file changed or is unreadable. Reselect it, then start again.")
    static let transferFailureLocalDestinationDetail = value("The Mac destination is unavailable. Choose another folder, then start again.")
    static let transferFailureQueuePersistenceDetail = value("Queue recovery storage failed. Resolve the warning above before starting another transfer.")
    static let transferFailureRestartRequiredDetail = value("This transfer could not be recovered safely. Remove it and start a new transfer.")
    static let transferFailureProtocolDetail = value("The secure transfer protocol ended unexpectedly. Reconnect Android, then start again.")
    static let transferFailureGenericDetail = value("The transfer could not finish. Check both devices, then start again.")

    static func completedTransfersRemovalResult(_ removed: Int, _ requested: Int) -> String {
        String(format: value("%d of %d completed transfers were removed. The remaining entries stay in Transfers."), removed, requested)
    }
    static let loadingDiagnostics = value("Loading diagnostics…")
    static let exportDiagnostics = value("Export Diagnostics")
    static let diagnosticsExportFailed = value("Diagnostics couldn’t be exported")
    static let diagnosticsExportFailedDetail = value("Choose another writable location and try again.")
    static let deviceHealth = value("Device health")
    static let deviceHealthDetail = value("A privacy-bounded snapshot from the authenticated Android session.")
    static let overview = value("Overview")
    static let device = value("Device")
    static let system = value("System")
    static let storage = value("Storage")
    static let battery = value("Battery")
    static let service = value("Service")
    static let recentIssues = value("Recent issues")
    static let notAvailable = value("Not available")
    static let apiLevel = value("API %d")
    static let totalStorage = value("%@ total")
    static let pairedProofVerified = value("Paired proof verified")
    static let errorDetailsStayPrivate = value("Details stay in the private diagnostic boundary")
    static let androidPermissions = value("Android permissions")
    static let sessionActivity = value("Service activity")
    static let diagnosticsUnavailable = value("Diagnostics are unavailable")
    static let diagnosticsSessionUnavailable = value("The authenticated session has ended. Reconnect the device to refresh health.")
    static let diagnosticsUnsupported = value("This Android endpoint does not grant the diagnostics capability.")
    static let diagnosticsInvalidResponse = value("Android returned an invalid diagnostics snapshot.")
    static let diagnosticsConnectionUnavailable = value("The health snapshot could not be refreshed over the secure session.")
    static let connected = value("Connected")
    static let available = value("Available")
    static let degraded = value("Degraded")
    static let unknown = value("Unknown")
    static let mediaLibrary = value("Media library")
    static let notificationsPermission = value("Notifications")
    static let sharedFolders = value("Shared folders")
    static let granted = value("Granted")
    static let denied = value("Denied")
    static let actionNeeded = value("Action needed")
    static let notApplicable = value("Not applicable")
    static let framesReceived = value("Frames received")
    static let framesSent = value("Frames sent")
    static let handshakes = value("Handshakes")
    static let authentications = value("Authentications")
    static let rejectedAuthentications = value("Rejected authentication")
    static let directoryRequests = value("Directory requests")
    static let diagnosticRequests = value("Diagnostic requests")
    static let bytesSent = value("Bytes sent")
    static let bytesReceived = value("Bytes received")
    static let transfersCompleted = value("Uploads completed")

    static func perSecond(_ rate: String) -> String {
        String(format: value("%@/s"), rate)
    }

    static func attempt(_ number: Int) -> String {
        String(format: value("Attempt %d"), number)
    }

    static func progress(_ confirmed: String, _ total: String) -> String {
        String(format: value("%@ of %@"), confirmed, total)
    }

    private static func value(_ key: String) -> String {
        localizationBundle.localizedString(forKey: key, value: key, table: nil)
    }
}
