import Foundation

enum AppStrings {
    private static let localizationBundle: Bundle = {
        if let resourceURL = Bundle.main.resourceURL,
           let bundle = Bundle(
               url: resourceURL.appendingPathComponent(
                   "DroidMatchMac_DroidMatchApp.bundle",
                   isDirectory: true
               )
           ) {
            return bundle
        }
        return .module
    }()

    static let appName = value("DroidMatch")
    static let devices = value("Devices")
    static let files = value("Files")
    static let transfers = value("Transfers")
    static let diagnostics = value("Diagnostics")
    static let localFirst = value("Local first")
    static let adbFoundation = value("USB discovery through the product ADB boundary")
    static let refresh = value("Refresh")
    static let refreshDevices = value("Refresh devices")
    static let deviceOverview = value("Your Android devices")
    static let deviceOverviewDetail = value("Private, local discovery. Hardware serials stay outside the interface.")
    static let visible = value("Visible")
    static let ready = value("Ready")
    static let transport = value("Transport")
    static let lookingForDevices = value("Looking for devices…")
    static let noDevices = value("No Android devices found")
    static let noDevicesDetail = value("Connect a device by USB, unlock it, and approve the ADB prompt if Android asks.")
    static let adbUnavailable = value("ADB is unavailable")
    static let discoveryTimedOut = value("Device discovery timed out")
    static let discoveryUnavailable = value("Device discovery is unavailable")
    static let staleDeviceDetail = value("The last device snapshot is shown as stale. Refresh before starting a session.")
    static let discoveryFailureDetail = value("Check the Android platform tools and try again.")
    static let androidDevice = value("Android device")
    static let trustedAndroidDevices = value("Trusted Android devices")
    static let trustedAndroidDevicesDetail = value("Pairing records saved securely in this Mac's Keychain.")
    static let trustedDevicesUnavailable = value("Saved trust records are temporarily unavailable.")
    static let noTrustedDevices = value("No Android devices are currently trusted.")
    static let lastUsed = value("Last used: %@")
    static let removeTrust = value("Remove trust")
    static let removeTrustedDevice = value("Remove trusted device?")
    static let removeTrustedDeviceDetail = value("%@ will need to pair again. Any active session will be disconnected first.")
    static let removeAndDisconnect = value("Remove and disconnect")
    static let keepDevice = value("Keep")
    static let stale = value("Stale")
    static let unauthorized = value("Approval needed")
    static let offline = value("Offline")
    static let unavailable = value("Unavailable")
    static let connect = value("Connect")
    static let reconnect = value("Reconnect")
    static let startPairing = value("Start pairing")
    static let disconnect = value("Disconnect")
    static let tryAgain = value("Try again")
    static let sessionIdle = value("No active session")
    static let connectingSecurely = value("Connecting securely…")
    static let connectingSecurelyDetail = value("Creating a private USB forward and checking the Android device identity.")
    static let pairingRequired = value("Pair this Mac")
    static let pairingRequiredDetail = value("On Android, open DroidMatch, enable Secure USB, then open the two-minute pairing window before continuing here.")
    static let startingPairing = value("Starting pairing…")
    static let startingPairingDetail = value("Waiting for the Android pairing window and a fresh device challenge.")
    static let confirmPairingCode = value("Confirm the pairing code")
    static let confirmPairingCodeDetail = value("Compare the six digits on both devices. Approve only when they match exactly.")
    static let finishingPairing = value("Securing the session…")
    static let finishingPairingDetail = value("Both approvals are being confirmed before credentials are stored and the session reconnects.")
    static let secureSessionReady = value("Secure session ready")
    static let secureSessionReadyDetail = value("Device identity and both session proofs are verified. File browsing is now available.")
    static let disconnecting = value("Disconnecting…")
    static let disconnectingDetail = value("Closing the session and removing its private ADB forward.")
    static let connectionFailed = value("Couldn’t connect securely")
    static let sessionDeviceUnavailable = value("The selected device is no longer connected. Refresh the device list and try again.")
    static let sessionDeviceNotReady = value("Unlock Android and approve the ADB prompt before connecting.")
    static let sessionTimedOut = value("The USB connection timed out. Check the cable and try again.")
    static let sessionPairingRejected = value("Pairing was not approved. Open a new pairing window on Android before retrying.")
    static let sessionIdentityChanged = value("The Android identity changed during pairing, so no trust was saved.")
    static let sessionCredentialsUnavailable = value("The saved pairing record is unavailable. Pair the device again.")
    static let sessionAuthenticationFailed = value("The saved pairing could not prove this device identity. Pair again before accessing files.")
    static let sessionConnectionUnavailable = value("Open DroidMatch on Android and enable Secure USB, then retry. Nothing was exposed and the USB forward was closed.")
    static let compareCodeWithDevice = value("Compare this code with the one shown on %@.")
    static let pairingCodeAccessibility = value("Pairing code %@")
    static let codesDoNotMatch = value("Codes don’t match")
    static let codesMatch = value("Codes match")
    static let filesNeedSession = value("Files need an authenticated session")
    static let filesNeedSessionDetail = value("Device discovery is live. File browsing will unlock after the product session boundary is connected.")
    static let transfersNeedSession = value("No active transfer session")
    static let transfersNeedSessionDetail = value("Connect and authenticate a device before starting or viewing transfers.")
    static let diagnosticsNeedSession = value("Session diagnostics are not connected yet")
    static let diagnosticsNeedSessionDetail = value("This product surface will use structured transport and permission state, never raw harness output.")
    static let authenticatedFiles = value("Authenticated Android files")
    static let back = value("Back")
    static let loadingFiles = value("Loading files…")
    static let folderIsEmpty = value("This location is empty")
    static let folderIsEmptyDetail = value("No items are visible with the Android permissions currently granted.")
    static let loadMore = value("Load more")
    static let filePermissionRequired = value("Android permission is required for this location.")
    static let fileLocationUnavailable = value("This Android location is no longer available.")
    static let fileOperationUnsupported = value("This provider does not support directory listing here.")
    static let fileResponseInvalid = value("Android returned an invalid directory response.")
    static let fileConnectionUnavailable = value("The directory could not be loaded over the secure session.")
    static let unnamedItem = value("Unnamed item")
    static let writable = value("Writable")
    static let openFolder = value("Open folder")
    static let download = value("Download")
    static let downloadFile = value("Download file")
    static let previewMedia = value("Preview media")
    static let loadingPreview = value("Loading preview…")
    static let previewUnavailable = value("Preview unavailable")
    static let showAsGrid = value("Show as Grid")
    static let showAsList = value("Show as List")
    static let downloadCouldNotStart = value("Download couldn’t start")
    static let downloadCouldNotStartDetail = value("The selected destination or Android file path is no longer valid.")
    static let upload = value("Upload")
    static let uploadCouldNotStart = value("Upload couldn’t start")
    static let uploadCouldNotStartDetail = value("Choose a supported file name and a writable Android directory.")
    static let newFolder = value("New Folder")
    static let folderName = value("Folder name")
    static let create = value("Create")
    static let folderCouldNotBeCreated = value("Folder couldn’t be created")
    static let folderNameInvalid = value("Choose a name without slashes or control characters.")
    static let folderAlreadyExists = value("An item with this name already exists.")
    static let folderPermissionRequired = value("Android no longer allows changes in this location.")
    static let folderParentUnavailable = value("This Android location is no longer available.")
    static let folderCreationUnsupported = value("This provider does not support creating folders here.")
    static let folderCreationUnavailable = value("The folder could not be created over the secure session.")
    static let rename = value("Rename")
    static let renameItem = value("Rename Item")
    static let newName = value("New name")
    static let itemCouldNotBeRenamed = value("Item couldn’t be renamed")
    static let delete = value("Delete")
    static let deleteItem = value("Delete this item?")
    static let deleteFileDetail = value("This file will be permanently removed from Android.")
    static let deleteFolderDetail = value("This folder and all of its contents will be permanently removed from Android.")
    static let itemCouldNotBeDeleted = value("Item couldn’t be deleted")
    static let searchFiles = value("Search this folder")
    static let noSearchResults = value("No matching items")
    static let noSearchResultsDetail = value("Try a different name in this folder.")
    static let select = value("Select")
    static let done = value("Done")
    static let deleteSelectedItems = value("Delete selected items?")
    static let deleteSelectedItemsDetail = value("All selected files, folders, and folder contents will be permanently removed from Android.")
    static let someItemsCouldNotBeDeleted = value("Some items couldn’t be deleted")
    static let dropFilesToUpload = value("Drop files to upload")
    static let droppedFilesInvalid = value("Some dropped files couldn’t be added")
    static let droppedFilesInvalidDetail = value("Drop up to 100 regular files with unique names into a writable Android folder.")
    static let downloadSelected = value("Download Selected")
    static let batchDownloadCouldNotStart = value("Selected files couldn’t be downloaded")
    static let batchDownloadCouldNotStartDetail = value("Select readable files with unique names and an empty destination folder.")

    static func selectedCount(_ count: Int) -> String {
        String(format: value("%d selected"), count)
    }
    static let dismiss = value("Dismiss")
    static let secureTransfers = value("Secure transfers")
    static let persistentQueueDetail = value("Pending work is saved privately for this authenticated device. Resume paused items after reconnecting.")
    static let queuePersistenceFailed = value("Queue recovery storage is unavailable. New transfers are blocked to avoid losing recovery state.")
    static let noTransfers = value("No transfers yet")
    static let noTransfersDetail = value("Download a readable Android file, or upload a local file into a writable Android directory.")
    static let pause = value("Pause")
    static let resume = value("Resume")
    static let cancel = value("Cancel")
    static let remove = value("Remove")
    static let transferQueued = value("Queued")
    static let transferRunning = value("Downloading")
    static let transferUploading = value("Uploading")
    static let transferRetrying = value("Retrying")
    static let transferPausing = value("Pausing")
    static let transferPaused = value("Paused")
    static let transferCompleted = value("Completed")
    static let transferFailed = value("Failed")
    static let transferCancelled = value("Cancelled")
    static let transferInterrupted = value("Interrupted")
    static let loadingDiagnostics = value("Loading diagnostics…")
    static let deviceHealth = value("Device health")
    static let deviceHealthDetail = value("A privacy-bounded snapshot from the authenticated Android session.")
    static let overview = value("Overview")
    static let device = value("Device")
    static let system = value("System")
    static let storage = value("Storage")
    static let battery = value("Battery")
    static let service = value("Service")
    static let recentIssues = value("Recent issues")
    static let notAvailable = value("Not available")
    static let apiLevel = value("API %d")
    static let totalStorage = value("%@ total")
    static let pairedProofVerified = value("Paired proof verified")
    static let errorDetailsStayPrivate = value("Details stay in the private diagnostic boundary")
    static let androidPermissions = value("Android permissions")
    static let sessionActivity = value("Service activity")
    static let diagnosticsUnavailable = value("Diagnostics are unavailable")
    static let diagnosticsSessionUnavailable = value("The authenticated session has ended. Reconnect the device to refresh health.")
    static let diagnosticsUnsupported = value("This Android endpoint does not grant the diagnostics capability.")
    static let diagnosticsInvalidResponse = value("Android returned an invalid diagnostics snapshot.")
    static let diagnosticsConnectionUnavailable = value("The health snapshot could not be refreshed over the secure session.")
    static let connected = value("Connected")
    static let available = value("Available")
    static let degraded = value("Degraded")
    static let unknown = value("Unknown")
    static let mediaLibrary = value("Media library")
    static let notificationsPermission = value("Notifications")
    static let sharedFolders = value("Shared folders")
    static let granted = value("Granted")
    static let denied = value("Denied")
    static let actionNeeded = value("Action needed")
    static let notApplicable = value("Not applicable")
    static let framesReceived = value("Frames received")
    static let framesSent = value("Frames sent")
    static let handshakes = value("Handshakes")
    static let authentications = value("Authentications")
    static let rejectedAuthentications = value("Rejected authentication")
    static let directoryRequests = value("Directory requests")
    static let diagnosticRequests = value("Diagnostic requests")
    static let bytesSent = value("Bytes sent")
    static let bytesReceived = value("Bytes received")
    static let transfersCompleted = value("Uploads completed")

    static func perSecond(_ rate: String) -> String {
        String(format: value("%@/s"), rate)
    }

    static func attempt(_ number: Int) -> String {
        String(format: value("Attempt %d"), number)
    }

    static func progress(_ confirmed: String, _ total: String) -> String {
        String(format: value("%@ of %@"), confirmed, total)
    }

    private static func value(_ key: String) -> String {
        localizationBundle.localizedString(forKey: key, value: key, table: nil)
    }
}
