import Foundation

enum AppStrings {
    private static let localizationBundle: Bundle = {
        if let resourceURL = Bundle.main.resourceURL,
           let bundle = Bundle(
               url: resourceURL.appendingPathComponent(
                   "DroidMatchMac_DroidMatchApp.bundle",
                   isDirectory: true
               )
           ) {
            return bundle
        }
        return .module
    }()

    static let appName = value("DroidMatch")
    static let devices = value("Devices")
    static let files = value("Files")
    static let transfers = value("Transfers")
    static let diagnostics = value("Diagnostics")
    static let localFirst = value("Local first")
    static let adbFoundation = value("USB discovery through the product ADB boundary")
    static let refresh = value("Refresh")
    static let refreshDevices = value("Refresh devices")
    static let deviceOverview = value("Your Android devices")
    static let deviceOverviewDetail = value("Private, local discovery. Hardware serials stay outside the interface.")
    static let visible = value("Visible")
    static let ready = value("Ready")
    static let transport = value("Transport")
    static let lookingForDevices = value("Looking for devices…")
    static let noDevices = value("No Android devices found")
    static let noDevicesDetail = value("Connect a device by USB, unlock it, and approve the ADB prompt if Android asks.")
    static let adbUnavailable = value("ADB is unavailable")
    static let discoveryTimedOut = value("Device discovery timed out")
    static let discoveryUnavailable = value("Device discovery is unavailable")
    static let staleDeviceDetail = value("The last device snapshot is shown as stale. Refresh before starting a session.")
    static let discoveryFailureDetail = value("Check the Android platform tools and try again.")
    static let androidDevice = value("Android device")
    static let stale = value("Stale")
    static let unauthorized = value("Approval needed")
    static let offline = value("Offline")
    static let unavailable = value("Unavailable")
    static let connect = value("Connect")
    static let reconnect = value("Reconnect")
    static let startPairing = value("Start pairing")
    static let disconnect = value("Disconnect")
    static let tryAgain = value("Try again")
    static let sessionIdle = value("No active session")
    static let connectingSecurely = value("Connecting securely…")
    static let connectingSecurelyDetail = value("Creating a private USB forward and checking the Android device identity.")
    static let pairingRequired = value("Pair this Mac")
    static let pairingRequiredDetail = value("On Android, open DroidMatch, enable Secure USB, then open the two-minute pairing window before continuing here.")
    static let startingPairing = value("Starting pairing…")
    static let startingPairingDetail = value("Waiting for the Android pairing window and a fresh device challenge.")
    static let confirmPairingCode = value("Confirm the pairing code")
    static let confirmPairingCodeDetail = value("Compare the six digits on both devices. Approve only when they match exactly.")
    static let finishingPairing = value("Securing the session…")
    static let finishingPairingDetail = value("Both approvals are being confirmed before credentials are stored and the session reconnects.")
    static let secureSessionReady = value("Secure session ready")
    static let secureSessionReadyDetail = value("Device identity and both session proofs are verified. File browsing is now available.")
    static let disconnecting = value("Disconnecting…")
    static let disconnectingDetail = value("Closing the session and removing its private ADB forward.")
    static let connectionFailed = value("Couldn’t connect securely")
    static let sessionDeviceUnavailable = value("The selected device is no longer connected. Refresh the device list and try again.")
    static let sessionDeviceNotReady = value("Unlock Android and approve the ADB prompt before connecting.")
    static let sessionTimedOut = value("The USB connection timed out. Check the cable and try again.")
    static let sessionPairingRejected = value("Pairing was not approved. Open a new pairing window on Android before retrying.")
    static let sessionIdentityChanged = value("The Android identity changed during pairing, so no trust was saved.")
    static let sessionCredentialsUnavailable = value("The saved pairing record is unavailable. Pair the device again.")
    static let sessionAuthenticationFailed = value("The saved pairing could not prove this device identity. Pair again before accessing files.")
    static let sessionConnectionUnavailable = value("Open DroidMatch on Android and enable Secure USB, then retry. Nothing was exposed and the USB forward was closed.")
    static let compareCodeWithDevice = value("Compare this code with the one shown on %@.")
    static let pairingCodeAccessibility = value("Pairing code %@")
    static let codesDoNotMatch = value("Codes don’t match")
    static let codesMatch = value("Codes match")
    static let filesNeedSession = value("Files need an authenticated session")
    static let filesNeedSessionDetail = value("Device discovery is live. File browsing will unlock after the product session boundary is connected.")
    static let transfersNeedSession = value("No active transfer session")
    static let transfersNeedSessionDetail = value("The tested transfer queue will appear here after lifecycle-owned session wiring is enabled.")
    static let diagnosticsNeedSession = value("Session diagnostics are not connected yet")
    static let diagnosticsNeedSessionDetail = value("This product surface will use structured transport and permission state, never raw harness output.")
    static let authenticatedFiles = value("Authenticated Android files")
    static let back = value("Back")
    static let loadingFiles = value("Loading files…")
    static let folderIsEmpty = value("This location is empty")
    static let folderIsEmptyDetail = value("No items are visible with the Android permissions currently granted.")
    static let loadMore = value("Load more")
    static let filePermissionRequired = value("Android permission is required for this location.")
    static let fileLocationUnavailable = value("This Android location is no longer available.")
    static let fileOperationUnsupported = value("This provider does not support directory listing here.")
    static let fileResponseInvalid = value("Android returned an invalid directory response.")
    static let fileConnectionUnavailable = value("The directory could not be loaded over the secure session.")
    static let unnamedItem = value("Unnamed item")
    static let writable = value("Writable")
    static let openFolder = value("Open folder")

    private static func value(_ key: String) -> String {
        localizationBundle.localizedString(forKey: key, value: key, table: nil)
    }
}
